inherit_from: .rubocop_todo.yml

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false
